services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   volumes:
  #     - ./zookeeper/data:/var/lib/zookeeper/data
  #     - ./zookeeper/datalog:/var/lib/zookeeper/log
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    ports:
      - 9097:9097
      - 19097:19097
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_ZOOKEEPER_CONNECT: 172.16.46.203:2181
      KAFKA_LISTENERS: INTERNAL://:19097,EXTERNAL://:9097
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://172.16.46.205:19097,EXTERNAL://172.16.46.205:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 3
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3


  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka:19092,192.168.137.100:19093,192.168.137.25:19094,192.168.137.225:19095,192.168.137.116:19096"

